Repository ValbionGroup/Comus-Party, pull requests merged in 2024-11, with the labels that each got.

#31 [CP-8] Correction des problèmes de connexion
  public/index.php
  src/controllers/controllerAuth.class.php
  src/models/CustomExceptions.php
  src/models/user.dao.php
Labels: bug, modification

#29 Ajout des tests pour la page de profil
  tests/ControllerFactoryTest.php
  tests/ControllerTest.php
  tests/PlayerDAOTest.php
  tests/PlayerTest.php
  tests/UserDAOTest.php
  tests/UserTest.php
  tests/controllerProfileTest.php
Labels: ajout

#28 Ajout des workflows
  .env.exemple
  .github/workflows/docs.yml
  .github/workflows/tests.yml
  Doxyfile
  src/models/article.class.php
  src/models/article.dao.php
  tests/.empty
Labels: ajout

#30 [CP-37] Afficher la page du profil - correction pour les test
  src/models/player.class.php
Labels: bug, modification

#37 [CP-37] Afficher la page du profil
  src/controllers/controllerProfile.class.php
Labels: documentation

#33 [CP-8] Se connecter
  src/routes.php
  tests/ControllerAuthTest.php
Labels: modification

#32 Ajout des tests pour la consultation des statistiques
  tests/StatisticsTest.php
Labels: ajout

#36 Ajout du test BD
  tests/.empty
  tests/DbTest.php
  tests/phpunit.xml
Labels: ajout

#38 style/configuration du header
  src/templates/layouts/default.twig
Labels: ajout

#41 features/gestion des erreurs - Ajout du traitement d'erreur avec pop-up
  config/twig.php
  public/index.php
  src/pages/errors.php
  src/routes.php
  src/templates/layouts/base.twig
Labels: ajout

#39 Ajout d'un fichier CNAME pour la publication de la documentation
  docs/html/CNAME
Labels: documentation

#45 🎨 Ajout d'un fond animé
  src/templates/layouts/base.twig
  src/templates/layouts/default.twig
  tailwind.config.js
Labels: modification

#44 💥 Ajout des Namespaces
  .idea/Code.iml
  include.php
  public/index.php
  src/Controllers/controller.class.php
  src/Controllers/controllerAuth.class.php
  src/Controllers/controllerFactory.class.php
  src/Controllers/controllerGame.class.php
  src/Controllers/controllerProfile.class.php
  src/Controllers/controllerShop.class.php
  src/Models/Exceptions/AuthentificationException.php
  src/Models/Exceptions/ControllerNotFoundException.php
  src/Models/Exceptions/ErrorHandler.php
  src/Models/Exceptions/MalformedRequestException.php
  src/Models/Exceptions/MethodNotFoundException.php
  src/Models/Exceptions/NotFoundException.php
  src/Models/Exceptions/RouteNotFoundException.php
  src/Models/Exceptions/UnauthorizedAccessException.php
  src/Models/Router.php
  src/Models/article.class.php
  src/Models/article.dao.php
  src/Models/db.class.php
  src/Models/game.class.php
  src/Models/game.dao.php
  src/Models/player.class.php
  src/Models/player.dao.php
  src/Models/statistics.class.php
  src/Models/user.class.php
  src/Models/user.dao.php
  src/models/CustomExceptions.php
  src/pages/errors.php
  src/routes.php
  src/templates/errors.twig
  tests/ArticleDAOTest.php
  tests/ArticleTest.php
  tests/ControllerAuthTest.php
  tests/ControllerFactoryTest.php
  tests/ControllerProfileTest.php
  tests/ControllerTest.php
  tests/DbTest.php
  tests/PlayerDAOTest.php
  tests/PlayerTest.php
  tests/StatisticsTest.php
  tests/UserDAOTest.php
  tests/UserTest.php
Labels: modification

#47 :lipstick: Modification de la disparirtion du message d'erreur
  src/templates/layouts/base.twig
Labels: modification

#48 [CP-40] Modifications mineures de la page d'accueil
  public/assets/js/home.js
  src/css/base.css
  src/templates/home.twig
  src/templates/layouts/base.twig
  tailwind.config.js
Labels: documentation, modification

#50 Ajout des styles communs
  composer.lock
  package-lock.json
  package.json
  src/templates/home.twig
  src/templates/login.twig
  tailwind.config.js
Labels: modification

#54 Création d'une template de facture
  src/templates/invoice.twig
Labels: ajout
