Repository ValbionGroup/Comus-Party, pull requests merged in 2024-12, with the labels that each got.

#56 Modification des styles de base
  tailwind.config.js
Labels: modification

#53 [CP-37] Afficher la page du profil
  src/templates/profil.twig
  tailwind.config.js
Labels: modification

#60 :ambulance: Estéban
  src/routes.php
Labels: invalide

#61 ⚡ Modification du nom d'une exception
  .idea/Code.iml
  include.php
  src/Controllers/controllerAuth.class.php
  src/Models/Exceptions/AuthenticationException.php
  tests/ControllerAuthTest.php
Labels: modification

#59 Mise à jour des couleurs
  tailwind.config.js
Labels: modification

#63 features/validation-formulaires
  src/Controllers/controllerAuth.class.php
  src/templates/login.twig
Labels: modification

#62 [CP-8] Se connecter
  src/Controllers/controllerAuth.class.php
  src/templates/login.twig
Labels: ajout

#35 [CP-4] Ajouter un article à son panier
  .idea/php.xml
  include.php
  public/assets/js/basket.js
  public/assets/js/shop.js
  src/Controllers/controllerBasket.class.php
  src/Controllers/controllerShop.class.php
  src/Models/article.class.php
  src/Models/article.dao.php
  src/routes.php
  src/scripts/shop.js
  src/templates/basket.twig
  src/templates/shop.twig
  tests/ArticleTest.php
Labels: ajout

#57 [CP-71] Vérification et envoi au SIB
  include.php
  public/index.php
  src/Controllers/controllerShop.class.php
  src/Models/Router.class.php
  src/Models/article.dao.php
  src/Models/invoice.class.php
  src/Models/invoice.dao.php
  src/routes.php
  src/templates/invoice.twig
  tests/InvoiceDAOTest.php
  tests/InvoiceTest.php
Labels: ajout

#65 Gestion des mot de passe oublié
  .idea/php.xml
  composer.json
  composer.lock
  config/mail.php
  include.php
  src/Controllers/controllerAuth.class.php
  src/Models/passwordResetToken.class.php
  src/Models/passwordResetToken.dao.php
  src/Models/user.dao.php
  src/routes.php
  src/templates/forgot-password.twig
  src/templates/reset-password.twig
Labels: ajout

#64 ✨ Suppression du compte
  config/twig.php
  src/Controllers/controller.class.php
  src/Controllers/controllerProfile.class.php
  src/Models/Exceptions/ErrorHandler.php
  src/Models/player.dao.php
  src/Models/user.dao.php
  src/routes.php
  src/templates/profil.twig
Labels: ajout

#68 [CP-69] :truck: Affichage des messages retravaillés
  config/twig.php
  include.php
  public/index.php
  src/Controllers/controller.class.php
  src/Controllers/controllerAuth.class.php
  src/Models/Exceptions/MessageHandler.php
  src/routes.php
  src/templates/layouts/base.twig
Labels: modification

#70 [CP-9] Accéder au formulaire de suggestion
  src/templates/home.twig
Labels: ajout

#69 :ambulance: Correction de l'appel d'une méthode qui n'était pas refactorisée
  src/Controllers/controllerAuth.class.php
  src/Controllers/controllerProfile.class.php
Labels: modification

#67 [CP-4] Ajouter un article à son panier
  public/assets/js/basket.js
  public/assets/js/shop.js
  src/Controllers/controllerAuth.class.php
  src/Controllers/controllerBasket.class.php
  src/templates/basket.twig
  src/templates/layouts/default.twig
  src/templates/shop.twig
Labels: modification

#74 🧪 Ajout des tests pour Mot de passe oublié [CP-69]
  src/Controllers/controllerAuth.class.php
  src/Models/db.class.php
  tests/PasswordResetTokenDAOTest.php
  tests/PasswordResetTokenTest.php
Labels: modification

#73 [CP-41] Selectionner un jeu
  public/assets/js/home.js
  src/Controllers/controllerGame.class.php
  src/Models/game.class.php
  src/Models/game.dao.php
  src/templates/home.twig
Labels: ajout

#66 [CP-70] Formulaire de paiement
  public/assets/js/checkout.js
  src/Controllers/controllerShop.class.php
  src/routes.php
  src/templates/basket.twig
  src/templates/checkout.twig
Labels: ajout

#76 ✨ Intégration de Google Analytics avec Axeptio
  public/assets/js/.empty
  public/assets/js/cookies.js
  src/templates/layouts/base.twig
Labels: ajout

#80 🔐 Ajout d'un "middleware"
  src/Models/Router.class.php
Labels: modification

#82 [CP-4] Ajouter un article à son panier
  public/assets/js/basket.js
  public/assets/js/shop.js
  src/Controllers/controllerBasket.class.php
  src/templates/layouts/base.twig
  src/templates/player/basket.twig
  src/templates/player/shop.twig
  tests/ArticleDAOTest.php
Labels: modification

#79 Ajout de la gestion de connexion du modérateur
  include.php
  src/Controllers/controllerAuth.class.php
  src/Models/moderator.class.php
  src/Models/moderator.dao.php
  src/Models/player.dao.php
  src/routes.php
  tests/ModeratorDAOTest.php
  tests/ModeratorTest.php
  tests/PlayerDAOTest.php
  tests/PlayerTest.php
  tests/UserTest.php
Labels: ajout

#86 [CP-4] Ajouter un article son panier
  public/assets/js/basket.js
  public/assets/js/shop.js
  src/templates/player/basket.twig
  src/templates/player/shop.twig
Labels: modification

#84 [CP-36] Refuser une proposition
  config/twig.php
  public/assets/js/dashboard.js
  src/Controllers/controllerDashboard.class.php
  src/Models/suggestion.dao.php
  src/routes.php
  src/templates/layouts/default.twig
  src/templates/moderator/dashboard.twig
Labels: ajout

#78 [CP-38] Modifier son avatar
  public/assets/js/profil.js
  src/Controllers/controllerProfile.class.php
  src/Models/article.dao.php
  src/routes.php
  src/templates/layouts/default.twig
  src/templates/player/profil.twig
Labels: ajout

#83 :arrow_up: Mise à jour des dépendances
  .idea/php.xml
  composer.json
  composer.lock
  src/Controllers/controllerAuth.class.php
Labels: modification

#85 :sparkles: Mise en place d'une fenêtre modale générale pour l'affichage de jeux
  public/assets/js/home.js
  src/Controllers/controllerGame.class.php
  src/Models/game.dao.php
  src/routes.php
  src/templates/player/home.twig
Labels: ajout

#87 [CP-34] Accepter une proposition
  public/assets/js/dashboard.js
  src/Controllers/controllerDashboard.class.php
  src/Models/suggestion.dao.php
  src/routes.php
  src/templates/moderator/dashboard.twig
  tests/ControllerSuggestionTest.php
  tests/SuggestionDAOTest.php
Labels: ajout

#88 [CP-30] Ajout des classes `GameRecord`
  .github/comusparty_export.sql
  composer.json
  composer.lock
  games/.gitignore
  include.php
  public/assets/fonts/.empty
  public/assets/img/.empty
  public/index.php
  src/Controllers/controller.class.php
  src/Controllers/controllerAuth.class.php
  src/Controllers/controllerGame.class.php
  src/Models/Exceptions/GameSettingsException.php
  src/Models/Exceptions/GameUnavailableException.php
  src/Models/Exceptions/MessageHandler.php
  src/Models/Router.class.php
  src/Models/game.dao.php
  src/Models/gameRecord.class.php
  src/Models/gameRecord.dao.php
  src/Models/player.dao.php
  tests/GameRecordDAOTest.php
  tests/GameRecordTest.php
Labels: ajout

#91 [CP-29] Créer une partie
  include.php
  package.json
  public/assets/js/game.js
  public/assets/js/home.js
  public/index.php
  src/App/Exception/AuthenticationException.php
  src/App/Exception/ControllerNotFoundException.php
  src/App/Exception/GameSettingsException.php
  src/App/Exception/GameUnavailableException.php
  src/App/Exception/MalformedRequestException.php
  src/App/Exception/MethodNotFoundException.php
  src/App/Exception/NotFoundException.php
  src/App/Exception/PaymentException.php
  src/App/Exception/RouteNotFoundException.php
  src/App/Exception/UnauthorizedAccessException.php
  src/App/MessageHandler.php
  src/App/Router.php
  src/App/Socket/Chat.php
  src/App/Socket/Game.php
  src/App/Validator.php
  src/Controllers/controller.class.php
  src/Controllers/controllerAuth.class.php
  src/Controllers/controllerDashboard.class.php
  src/Controllers/controllerFactory.class.php
  src/Controllers/controllerGame.class.php
  src/Controllers/controllerProfile.class.php
  src/Controllers/controllerShop.class.php
  src/Controllers/controllerSuggestion.class.php
  src/Models/article.dao.php
  src/Models/gameRecord.class.php
  src/Models/gameRecord.dao.php
  src/routes.php
  src/templates/layouts/base.twig
  src/templates/layouts/default.twig
  src/templates/player/game-settings.twig
  src/templates/player/home.twig
  tailwind.config.js
  tests/ControllerAuthTest.php
  tests/ControllerFactoryTest.php
  tests/ControllerProfileTest.php
  tests/GameRecordTest.php
  ws-server.php
Labels: ajout

#90 :memo: Ajout du `README` principal
  README.md
Labels: documentation
