Repository ValbionGroup/Comus-Party, pull requests merged in 2025-02, with the labels that each got.

#141 Accessibilité : Mise en place du feedback sur les formulaires
  src/Controllers/controllerAuth.class.php
  src/Controllers/controllerProfile.class.php
  src/assets/css/base.css
  src/assets/js/authentication.js
  src/assets/js/checkout.js
  src/assets/js/common.js
  src/assets/js/login.js
  src/assets/js/profil.js
  src/assets/js/reset-password.js
  src/assets/js/sign-up.js
  src/templates/login.twig
  src/templates/player/checkout.twig
  src/templates/player/profile.twig
  src/templates/reset-password.twig
  src/templates/sign-up.twig
  tests/ControllerAuthTest.php
Labels: ajout

#144 [CP-101] Afficher les détails d'un signalement
  src/Controllers/controllerDashboard.class.php
  src/Models/report.dao.php
  src/assets/js/dashboard.js
  src/routes.php
  src/templates/moderator/dashboard.twig
Labels: ajout

#147 Ajout de la gestion de Captcha
  .env.exemple
  composer.lock
  config/const.php
  package-lock.json
  package.json
  src/Controllers/controllerAuth.class.php
  src/assets/js/common.js
  src/assets/js/login.js
  src/assets/js/sign-up.js
  src/routes.php
  src/templates/layouts/base.twig
  src/templates/login.twig
  src/templates/sign-up.twig
  tailwind.config.js
  tests/ControllerAuthTest.php
Labels: ajout

#153 Correctifs mineurs
  src/App/Mailer.php
  src/Controllers/controllerAuth.class.php
  src/assets/js/common.js
  src/assets/js/login.js
  src/assets/js/sign-up.js
  src/templates/login.twig
  src/templates/sign-up.twig
Labels: modification

#154 :bug: Correction de tous les formulaires qui utilisaient du AJAX
  src/templates/login.twig
  src/templates/player/checkout.twig
  src/templates/player/profile.twig
  src/templates/sign-up.twig
Labels: bug, modification

#150 fix/issues/148 problème de vérification de mot de passe lors de linscription
  composer.lock
  package-lock.json
  package.json
  src/Controllers/controllerAuth.class.php
  src/assets/js/sign-up.js
  src/routes.php
Labels: bug, modification

#149 [CP- 96] Voir les signalements non traités en direct
  src/assets/js/dashboard.js
  src/routes.php
  src/templates/moderator/dashboard.twig
Labels: ajout

#155 Ajout d'une case `Se souvenir de moi`
  .github/comusparty_export.sql
  include.php
  src/App/Cookie.php
  src/App/Router.php
  src/Controllers/controllerAuth.class.php
  src/Models/rememberToken.class.php
  src/Models/rememberToken.dao.php
  src/assets/js/login.js
  src/routes.php
  src/templates/login.twig
  tests/ControllerAuthTest.php
  tests/RememberTokenTest.php
Labels: ajout
