Repository ValbionGroup/Comus-Party, pull requests merged in 2025-03, with the labels that each got.

#162 :bug: Correction de la méthode `getAllReports()` qui n'existait pas
  src/Controllers/controllerDashboard.class.php
  src/routes.php
Labels: ajout

#164 Désactivation du bouton si le captcha n'est pas valide
  src/assets/js/common.js
  src/assets/js/login.js
  src/assets/js/sign-up.js
  src/templates/forgot-password.twig
  src/templates/login.twig
  src/templates/player/profile.twig
  src/templates/reset-password.twig
  src/templates/sign-up.twig
Labels: modification

#166 Correctifs des données reçues et envoyés des/aux jeux
  games/README.md
  src/Controllers/controllerGame.class.php
Labels: bug, modification

#168 Correction de la logique de fonctionnement des jeux
  games/README.md
  src/Controllers/controllerGame.class.php
Labels: modification

#169 Ajout de fonctions gloables pour les retours en JSON
  src/App/MessageHandler.php
Labels: ajout

#175 Correction du validateur
  src/Controllers/controllerAuth.class.php
  src/Controllers/controllerProfile.class.php
Labels: bug, modification

#174 Correction du chemin d'accès aux images des jeux
  src/assets/js/home.js
Labels: modification

#173 :pencil2: Faute de frappe dans le nom de la modale de signalement
  src/templates/modal-report.twig
Labels: modification

#170 [CP-22] Sanctionner un joueur
  include.php
  src/App/Sockets/Chat.php
  src/Controllers/controllerGame.class.php
  src/Controllers/controllerProfile.class.php
  src/Models/game.dao.php
  src/Models/penalty.class.php
  src/Models/penalty.dao.php
  src/Models/report.class.php
  src/Models/report.dao.php
  src/assets/js/dashboard.js
  src/assets/js/game.js
  src/routes.php
  src/templates/moderator/dashboard.twig
  src/templates/moderator/modal-penalty.twig
Labels: ajout

#178 🔑 Ajout d'un token pour authentifier le serveur de jeu
  .github/comusparty_export.sql
  games/README.md
  src/Controllers/controllerGame.class.php
  src/Models/gameRecord.class.php
  src/Models/gameRecord.dao.php
  src/routes.php
  tests/GameRecordTest.php
Labels: ajout

#177 Vérification de la présence des joueurs à la fin d'une partie
  games/README.md
  src/Controllers/controllerGame.class.php
  src/routes.php
Labels: modification

#184 :sparkles: Vérification de la présence du chat avant d'exécuter le corps des fonctions
  src/assets/js/game.js
Labels: modification

#188 :bug: Inversion de l'ordre de chargement des fichiers JavaScript
  src/templates/layouts/base.twig
Labels: modification

#186 :pencil2: Correction de la requête de sélection des joueurs
  src/Models/player.dao.php
Labels: modification

#200 Vérification de l'objet lors de l'envoi d'une suggestion
  src/Controllers/ControllerSuggestion.class.php
  src/assets/js/home.js
  src/templates/player/home.twig
Labels: modification

#199 Modification de la taille des code pour les parties
  src/Controllers/ControllerGame.class.php
Labels: modification

#201 Correction de l'issue #191
  src/App/Sockets/Game.php
  src/App/Validator.php
  src/Controllers/ControllerGame.class.php
  src/Models/gameRecord.dao.php
  src/assets/js/game.js
  src/templates/player/game-settings.twig
Labels: bug, modification, ajout

#204 [193] Modification de la longueur maximum d'un pseudonyme
  .github/comusparty_export.sql
  src/Controllers/ControllerAuth.class.php
  src/Controllers/ControllerProfile.class.php
  src/assets/js/profil.js
  src/assets/js/sign-up.js
Labels: bug, modification

#205 [195] Impossible de se connecter quand les champs sont saisis par le navigateur
  src/assets/js/login.js
Labels: bug, modification

#206 :sparkles: Mise à jour des variables globales Twig lors du chargement
  src/Controllers/ControllerGame.class.php
Labels: bug, modification

#207 [171] Cas avec aucun article dans la boutique et aucun jeux
  src/templates/player/home.twig
  src/templates/player/shop.twig
Labels: modification

#219 [215] Correction rechercher une partie en attente de joueurs
  src/Controllers/ControllerGame.class.php
  src/Models/gameRecord.class.php
  src/Models/gameRecord.dao.php
Labels: bug, modification, ajout

#218 [216] Suppression de la partie lors du départ du dernier joueur
  src/Controllers/ControllerGame.class.php
Labels: bug, modification

#220 [217] Modification du mot de passe après un mot de passe oublié
  src/Controllers/ControllerAuth.class.php
  src/assets/js/login.js
  src/assets/js/reset-password.js
  src/assets/js/sign-up.js
  src/routes.php
Labels: bug, modification

#211 :bug: Traitement des caractères spéciaux
  src/assets/js/game.js
Labels: modification
