Repository ValbionGroup/Comus-Party, pull requests merged in 2025-01, with the labels that each got.

#95 :pencil2: Attente du retour de la requête XHR pour ouvrir la fenêtre modale
  public/assets/js/home.js
Labels: modification

#89 📧 Ajout d'une classe `Mailer`
  include.php
  src/Models/mailer.class.php
  src/templates/forgot-password.twig
  src/templates/mail.twig
  src/templates/reset-password.twig
Labels: ajout

#92 [CP-39] Modifier sa bannière
  public/assets/js/profil.js
  src/Controllers/controllerProfile.class.php
  src/Models/article.dao.php
  src/routes.php
  src/templates/layouts/default.twig
  src/templates/player/profil.twig
Labels: ajout

#94 :bug: Correction de la requête de la méthode `findWithDetailByUuid()`
  src/Models/player.dao.php
Labels: modification

#96 :sparkles: Ajout d'un attribut `token` associés à la relation entre un joueur et une partie
  .github/comusparty_export.sql
  src/Models/gameRecord.dao.php
Labels: ajout

#93 [CP-30] Lancer une partie
  .github/comusparty_export.sql
  games/README.md
  include.php
  public/assets/js/game.js
  public/assets/js/home.js
  public/index.php
  src/App/Exceptions/AuthenticationException.php
  src/App/Exceptions/ControllerNotFoundException.php
  src/App/Exceptions/GameSettingsException.php
  src/App/Exceptions/GameUnavailableException.php
  src/App/Exceptions/MalformedRequestException.php
  src/App/Exceptions/MethodNotFoundException.php
  src/App/Exceptions/NotFoundException.php
  src/App/Exceptions/PaymentException.php
  src/App/Exceptions/RouteNotFoundException.php
  src/App/Exceptions/UnauthorizedAccessException.php
  src/App/Router.php
  src/App/Sockets/Chat.php
  src/App/Sockets/Game.php
  src/Controllers/controller.class.php
  src/Controllers/controllerAuth.class.php
  src/Controllers/controllerBasket.class.php
  src/Controllers/controllerDashboard.class.php
  src/Controllers/controllerFactory.class.php
  src/Controllers/controllerGame.class.php
  src/Controllers/controllerProfile.class.php
  src/Controllers/controllerShop.class.php
  src/Models/article.dao.php
  src/Models/db.class.php
  src/Models/gameRecord.class.php
  src/Models/gameRecord.dao.php
  src/Models/invoice.dao.php
  src/Models/passwordResetToken.dao.php
  src/Models/user.dao.php
  src/routes.php
  src/templates/player/game-settings.twig
  src/templates/player/in-game.twig
  tests/ArticleDAOTest.php
  tests/ControllerAuthTest.php
  tests/ControllerProfileTest.php
  tests/ControllerTest.php
  tests/DbTest.php
  tests/GameRecordDAOTest.php
  tests/GameRecordTest.php
  tests/UserDAOTest.php
Labels: modification

#99 [CP-73] Afficher le classement des joueurs
  include.php
  public/assets/js/ranking.js
  src/Controllers/controllerAuth.class.php
  src/Controllers/controllerRanking.class.php
  src/Models/player.class.php
  src/Models/player.dao.php
  src/Models/statistics.class.php
  src/routes.php
  src/templates/layouts/default.twig
  src/templates/ranking.twig
Labels: ajout

#102 [CP-39] Ajout des tests
  tests/ArticleDAOTest.php
Labels: modification

#103 💄 Ajout des logos dans l'interface
  public/assets/img/cp-icon-v1.png
  public/assets/img/cp-logo-v2-without-bg.png
  src/templates/layouts/authentification.twig
  src/templates/layouts/base.twig
  src/templates/layouts/default.twig
Labels: modification

#106 [CP-78] Formulaire de paiement
  public/assets/js/checkout.js
  src/Controllers/controllerShop.class.php
  src/Models/invoice.dao.php
  src/Models/mailer.class.php
  src/routes.php
  src/templates/player/checkout.twig
  src/templates/player/successPayment.twig
Labels: ajout

#98 [CP-48] Participer à une partie en tant qu’inscrit
  .github/comusparty_export.sql
  public/assets/js/common.js
  public/assets/js/home.js
  src/Controllers/controllerGame.class.php
  src/Models/gameRecord.class.php
  src/Models/gameRecord.dao.php
  src/routes.php
  src/templates/layouts/base.twig
  src/templates/player/game-settings.twig
  src/templates/player/home.twig
  tests/GameRecordTest.php
Labels: ajout

#107 Terminaison d'une partie
  include.php
  public/assets/js/game.js
  src/Controllers/controllerAuth.class.php
  src/Controllers/controllerGame.class.php
  src/Models/eloCalculator.class.php
  src/Models/gameRecord.dao.php
  src/Models/player.dao.php
  src/routes.php
  src/templates/player/game-settings.twig
  src/templates/player/in-game.twig
  ws-server.php
Labels: ajout

#100 [CP-3] Selectionner un produit acheter
  src/templates/player/shop.twig
Labels: modification

#101 [CP-38] Ajout des tests
  src/Models/article.dao.php
  tests/ArticleDAOTest.php
Labels: modification

#97 ✨ Ajout du système de lancement du jeu
  public/assets/js/game.js
  src/Controllers/controllerGame.class.php
  src/Models/gameRecord.dao.php
Labels: modification

#111 fix/correction-petit-bugs
  src/Controllers/controllerGame.class.php
  src/Models/gameRecord.dao.php
Labels: modification

#112 Diverses corrections mineures
  games/README.md
  public/.gitignore
  src/Controllers/controllerGame.class.php
  src/Models/player.dao.php
  src/routes.php
  src/templates/player/game-settings.twig
Labels: modification

#114 Nouvelles corrections mineures
  Doxyfile
  README.md
  games/README.md
  public/assets/js/game.js
  src/Controllers/controllerGame.class.php
  src/Models/gameRecord.dao.php
  src/routes.php
  src/templates/player/game-settings.twig
  tailwind.config.js
Labels: modification

#118 [CP-73] Afficher le classement des joueurs
  src/Models/player.class.php
  src/Models/player.dao.php
Labels: modification

#120 🐛 Correction d'un problème lors de la finalisation du jeu
  composer.json
  public/assets/js/checkout.js
  public/assets/js/profil.js
  src/Controllers/controllerGame.class.php
  src/routes.php
Labels: bug, modification

#123 :sparkles: Réinitialisation du champ de texte après la saisie
  public/assets/js/profil.js
Labels: modification

#126 [CP-19] Consulter la liste des signalements
  .github/comusparty_export.sql
  include.php
  public/assets/js/dashboard.js
  src/Controllers/controllerDashboard.class.php
  src/Models/report.class.php
  src/Models/report.dao.php
  src/templates/moderator/dashboard.twig
Labels: ajout

#122 [CP-94] Parler dans le chat en jeu
  public/assets/js/common.js
  public/assets/js/game.js
  public/assets/js/ranking.js
  src/App/Sockets/Chat.php
  src/Controllers/controllerProfile.class.php
  src/Controllers/controllerRanking.class.php
  src/Models/player.dao.php
  src/routes.php
  src/templates/player/game-settings.twig
  src/templates/ranking.twig
Labels: ajout

#125 🐛 Correction du système de réinitialisation du mot de passe en cas d'oubli
  .github/comusparty_export.sql
  src/Controllers/controllerAuth.class.php
  src/templates/layouts/base.twig
Labels: bug, modification

#130 :lipstick: Ajout des icones et du manifest
  public/apple-touch-icon.png
  public/favicon-96x96.png
  public/favicon.ico
  public/favicon.svg
  public/site.webmanifest
  public/web-app-manifest-192x192.png
  public/web-app-manifest-512x512.png
  src/templates/layouts/base.twig
Labels: ajout

#129 :lipstick: Centrage du texte dans les boutons du profil
  src/templates/player/profil.twig
Labels: modification

#134 :bug: Correction de la méthode `update()`
  src/Models/user.dao.php
Labels: bug, modification

#127 [CP-95] Voir les modifications de partie en direct
  public/assets/js/game.js
  src/App/Sockets/Chat.php
  src/App/Sockets/Game.php
  src/templates/layouts/default.twig
  src/templates/player/game-settings.twig
  ws-server.php
Labels: modification

#116 [CP-3] Sélectionner un produit à acheter
  public/assets/js/shop.js
  src/Controllers/controllerBasket.class.php
  src/Controllers/controllerShop.class.php
  src/templates/player/shop.twig
Labels: modification

#137 🩹 Changement de controller pour la fonction
  src/Controllers/controllerAuth.class.php
  src/Controllers/controllerProfile.class.php
  src/routes.php
Labels: modification

#142 Correction disabled btn Confirmer
  public/assets/js/profil.js
  src/templates/player/profil.twig
Labels: modification

#138 Ajout gestion des erreurs en direct
  public/assets/js/profil.js
  src/templates/player/profil.twig
Labels: modification

#135 ✨ Ajout du système de sauvegarde et de restauration de la base de donnée
  .env.exemple
  .github/comusparty_export.sql
  .gitignore
  backup.sh
  composer.json
  config/const.php
  restore.sh
  src/App/Db.php
  src/Controllers/controller.class.php
  tests/ArticleDAOTest.php
  tests/ModeratorDAOTest.php
Labels: ajout

#143 Correction du chat de partie en direct
  public/assets/js/game.js
Labels: bug, modification

#139 Accessibilité : Adaptation des formulaires pour favoriser l'incitation
  public/assets/js/authentication.js
  public/assets/js/profil.js
  public/assets/js/reset-password.js
  src/Controllers/controllerAuth.class.php
  src/templates/forgot-password.twig
  src/templates/login.twig
  src/templates/player/checkout.twig
  src/templates/player/profil.twig
  src/templates/reset-password.twig
  src/templates/sign-up.twig
Labels: ajout

#140 Obfuscation et minification du code
  .gitignore
  package-lock.json
  package.json
  public/.gitignore
  src/Controllers/controllerProfile.class.php
  src/assets/css/base.css
  src/assets/js/authentication.js
  src/assets/js/basket.js
  src/assets/js/checkout.js
  src/assets/js/common.js
  src/assets/js/cookies.js
  src/assets/js/dashboard.js
  src/assets/js/game.js
  src/assets/js/home.js
  src/assets/js/profil.js
  src/assets/js/ranking.js
  src/assets/js/reset-password.js
  src/assets/js/shop.js
  src/templates/layouts/base.twig
  src/templates/moderator/dashboard.twig
  src/templates/player/basket.twig
  src/templates/player/checkout.twig
  src/templates/player/game-settings.twig
  src/templates/player/home.twig
  src/templates/player/in-game.twig
  src/templates/player/profile.twig
  src/templates/player/shop.twig
  src/templates/ranking.twig
  src/templates/sign-up.twig
  tailwind.config.js
  terser.config.js
Labels: modification
